[tool.cibuildwheel]
manylinux-x86_64-image = "manylinux_2_28"
# No PyPy for now, we are using c++17 language features that don't compile for PyPy ATM.
skip = "cp39-*"
environment = { CIBW_BUILD_VERBOSITY = "1", MAKEFLAGS = "-j4" }

[[tool.cibuildwheel.overrides]]
select = "*manylinux_2_2*"
before-all = """apt-get --assume-yes update; apt-get --assume-yes install net-snmp net-snmp-dev openssl libssl-dev;"""

[[tool.cibuildwheel.overrides]]
select = "*musllinux*"
before-all = "apk add net-snmp-dev openssl openssl-dev;"

[tool.cibuildwheel.linux]
before-all = """yum -y update; yum -y install net-snmp net-snmp-devel openssl openssl-devel;"""
repair-wheel-command = "auditwheel repair -w {dest_dir} {wheel}"

[tool.cibuildwheel.macos]
environment = { PATH = "/opt/homebrew/bin:/usr/local/bin:$PATH", MACOSX_DEPLOYMENT_TARGET = "15.0" }
archs = "arm64"
before-all = "HOMEBREW_NO_AUTO_UPDATE=1 brew install openssl@3 net-snmp"
repair-wheel-command = "delocate-wheel --require-archs {delocate_archs} -w {dest_dir} -v {wheel}"

[tool.cibuildwheel.windows]
archs = ["AMD64", "x86", "ARM64"]
test-skip = "*-win_arm64"
before-build = "python -m pip install delvewheel"
environment = { EZSNMP_NETSNMP_USE_DLL = "1" }
environment-pass = ["EZSNMP_NETSNMP_INCLUDE_DIR", "EZSNMP_NETSNMP_LIB_DIR", "EZSNMP_NETSNMP_BIN_DIR", "EZSNMP_OPENSSL_BIN_DIR", "EZSNMP_OPENSSL_INCLUDE_DIR", "EZSNMP_OPENSSL_LIB_DIR"]
repair-wheel-command = [
  "delvewheel show --add-path \"%EZSNMP_NETSNMP_BIN_DIR%;%EZSNMP_OPENSSL_BIN_DIR%\" --no-dll \"msvcp140.dll;msvcp140_1.dll;msvcp140_2.dll;msvcp140_atomic_wait.dll;msvcp140_codecvt_ids.dll;vcruntime140_1.dll\" {wheel}",
  "delvewheel repair --add-path \"%EZSNMP_NETSNMP_BIN_DIR%;%EZSNMP_OPENSSL_BIN_DIR%\" --no-dll \"msvcp140.dll;msvcp140_1.dll;msvcp140_2.dll;msvcp140_atomic_wait.dll;msvcp140_codecvt_ids.dll;vcruntime140_1.dll\" -w {dest_dir} {wheel}",
]

[build-system]
build-backend = "setuptools.build_meta"
requires = [
   "setuptools == 84.0.0",
    "wheel == 0.48.0",
    "swig==4.5.0",
]

[tool.pytest.ini_options]
pythonpath = ["python_tests", "."]
addopts = [
    "--import-mode=importlib",
]
norecursedirs = [
"docker",
"integration_tests",
]