services:
  fedora42_snmp_container:
    build:
      context: ../../
      dockerfile: docker/fedora42_netsnmp_5.9/Dockerfile
    container_name: fedora42_snmp_container
    volumes:
      - ../../:/ezsnmp
    working_dir: /ezsnmp
    entrypoint: ["/usr/local/bin/DockerEntry.sh"]
