# Refer to the following link for help
# https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

name: PyPI Distributions
concurrency: build_and_publish_to_pypi
on:
  release:
    types: [published]

jobs:
  verify-syntax:
    permissions: { contents: read }
    uses: ./.github/workflows/verify_syntax.yml
  build_wheels:
    needs: verify-syntax
    name: Build wheels on ${{ matrix.os }} (${{ matrix.arch }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64
          - os: macos-latest
            arch: arm64
          - os: windows-latest
            arch: AMD64
          - os: windows-latest
            arch: x86
          - os: windows-latest
            arch: ARM64

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v5

      - name: Build and upload wheels
        uses: ./.github/actions/build-wheels
        with:
          os: ${{ matrix.os }}
          arch: ${{ matrix.arch }}
          job-index: ${{ strategy.job-index }}

  build-n-publish-pypi:
    name: Build and Publish To PyPi
    runs-on: ubuntu-latest
    environment: build_and_publish_to_pypi
    permissions:
      id-token: write
    needs: build_wheels

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v5

      - name: Build and publish distribution
        uses: ./.github/actions/build-and-publish-distribution
        with:
          target: pypi
